[package]
name = "riscv_emu"
version = "0.1.0"
edition = "2024"

[features]
hitf = []
semihosting = []
headless = []

[dependencies]
bitfield = "0.19.1"
clap = { version = "4.6.1", features = ["derive"] }
eframe = "0.34.1"
egui_extras = "0.34.1"
elf = "0.8.0"
ihex = "3.0.0"
ntest = "0.9.3"
rfd = "0.17.2"
